In [24]:
import numpy as np

# Indexing in 1-D Array

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

find an index value

In [4]:
arr[8]

8

Get values in a range , just like list using slice notation

In [5]:
arr[1:5] # both 1 and 5 represent index values (indexing starts from 0) 

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

Remove stop or start point to go ahead and indicate to get everything else in the array or everything from beginning of the array

In [7]:
arr[:6]    # everything upto 5th index i.e 6th element

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]   # starts excluding 4th index and 5th element

array([ 5,  6,  7,  8,  9, 10])

numpy arrays differ from normal python list because of their ability to broadcast

In [9]:
arr[0:5] = 100 # set first 5 elements value as 100 each

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

we can reset the arr

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

slice of array

In [13]:
slice_of_array = arr [0:6]

In [14]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

broad-cast an array

In [15]:
slice_of_array[:] = 101

In [16]:
slice_of_array

array([101, 101, 101, 101, 101, 101])

In [17]:
arr # if we call original arr , values changed to 101

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

Above data is not copied , just viewed to original array . Reason Numpy does that to avoid memory issues for very large arrays . Meaning , Numpy will not automatically set copies of arrays . If we required a copy instead of reference to the original array we can specifically specify copy . Like below e.g

In [18]:
arr_copy = arr.copy() # 

In [19]:
arr 

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [20]:
arr_copy

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

In [21]:
arr_copy[:] = 51

In [22]:
arr_copy

array([51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51])

In [23]:
arr 

array([101, 101, 101, 101, 101, 101,   6,   7,   8,   9,  10])

If we want to grab a slice of an array and set it as a variable without explicitly saying that
we want dot copy of that array, we should keep in mind we are just viewing a link to that array and 
the changes we did will actually effect to that original array.

# Indexing in 2D array or Matrix

In [25]:
arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [26]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

2 methods for extracting 

In [29]:
arr_2D[0][0]  # [row][column] 

5

In [30]:
arr_2D[0,0]  # above can be written as like this

5

In [28]:
arr_2D[0]   # [row]

array([ 5, 10, 15])

Grab single element from chunks of array i.e create sub-matrix from a matrix

In [31]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr_2D[:2] # only rows

array([[ 5, 10, 15],
       [20, 25, 30]])

# Conditional selection

In [34]:
arr = np.arange(1,12)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
bool_arr = arr > 5

In [38]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

Conditional selection

In [39]:
arr[bool_arr] # print truthy value

array([ 6,  7,  8,  9, 10, 11])

Previous can be written in one line 

In [40]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11])

In [41]:
arr[arr<3]

array([1, 2])